### ISSUE TITLE
Frozen Graph 

### ISSUE THREAD

**Issue by madrugou** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#11]
I was able to perform the training correctly, I had some problems with the tensorflow version, but it has been fixed.

I am having problems running **exporter_main_v2.py** in an environment with **tesorflow 2.2.0**, but I can run it in another environment with **tensorflow 2.4.1**.

Error with tensorflow-gpu 2.2.0:
 ```code
TypeError: map_fn_v2() got an unexpected keyword argument 'fn_output_signature'
 ```

I would like to export the **frozen_graph.pb** file to do the inference in **C++**, but when I run the command **python export_main_v2.py**, it only creates the saved_model.pb, how can I extract or convert this model into a frozen_graph?

**Comment by TannerGilbert** [comment]
Sorry for the late reply. You should be able to use the SavedModel in C++ as shown in ["Tensorflow 2.x C++ API for object detection (inference)"](https://medium.com/@reachraktim/using-the-new-tensorflow-2-x-c-api-for-object-detection-inference-ad4b7fd5fecc).
