### ISSUE TITLE
Custom Mask-RCNN-Test images

### ISSUE THREAD

**Issue by kavi0786** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#15]
Hello, how to test the images after getting inference graph. 

Run in colab notebook: Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model. Once trained, how we can test images using inference graph. Thanks in advance...

**Comment by NyanSwanAung** [comment]
@kavi0786  Follow this [issue.](https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model/issues/12#issuecomment-855258857)

**Comment by NyanSwanAung** [comment]
@kavi0786  Follow this [issue.](https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model/issues/12#issuecomment-855258857)
