### ISSUE TITLE
Tensorflow-Object detection-API-test images

### ISSUE THREAD

**Issue by kavi0786** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#16]
Sir, i have completed training using "TensorFlow-API-train-custom-Mask-RCNN" code in this repository. Once trained , without exporting the inference graph and saved model, in google drive, how we can infer the test images after training in this code. Thanks in advance...

Kavitha

**Comment by TannerGilbert** [comment]
Please take a look at the last part of my [Tensorflow_2_Object_Detection_Train_model.ipynb notebook](https://github.com/TannerGilbert/Tensorflow-Object-Detection-API-Train-Model/blob/master/Tensorflow_2_Object_Detection_Train_model.ipynb).

**Comment by kavi0786** [comment]
Thank you sir,...I got test code in the "Tensorflow-Object-Detection-API-Train-Model.ipynb" file...

Thank you for prompt response .....


Regards
Kavitha
