### ISSUE TITLE
Conversion to TFlite

### ISSUE THREAD

**Issue by TranATT** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#19]
Hi Tanner is it possible to convert this model to TFlite. And if it is do we need the variables provided too in addition to the saved model?

**Comment by TannerGilbert** [comment]
Yes it is possible, but I'm not sure if the files are needed. For an example check out my [Tensorflow-Lite-Object-Detection-with-the-Tensorflow-Object-Detection-API repository](https://github.com/TannerGilbert/Tensorflow-Lite-Object-Detection-with-the-Tensorflow-Object-Detection-API).

**Comment by TranATT** [comment]
Thank you for replying, I will take a look at it!
