### ISSUE TITLE
Training getting stuck at the starting checkpoint

### ISSUE THREAD

**Issue by nkshelby** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#2]
Hi, I am facing an issue in training my custom model. I've done all the steps and got to the second last step in which training happens. Apparently, my training got stuck on checkpoint 1, it's not advancing any further also it's not showing me any errors. Help will be appreciated, Thank You

My system's specification are:
Processor: Core i5 3rd Gen 3.2 GHz
RAM: 12 GB
and I am using Anaconda.

**Comment by nkshelby** [comment]
Actually, I checked the tensorboard. My system's training is on track but it's not saving any checkpoint.

**Comment by TannerGilbert** [comment]
I haven't experienced this myself therefore it's quite hard for me to say what causes the problem. It might be a good idea to open an issue on the [models repository](https://github.com/tensorflow/models) so more people can see it.
