### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by RoshanKattil** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#23]
Hi I am trying to python use_protobuf.py <path to directory> <path to protoc file> but whenever I run it I get this
![Screenshot (53)_LI](https://user-images.githubusercontent.com/46833875/147655023-fb717168-2b18-4a23-9ae2-441385b5482d.jpg)

I've checked the other steps and they appear to be correct is anybody else having this issue or know how to fix it?

**Comment by AbdullahJirjees** [comment]
I am keep getting this error, I tried the code on windows and Ubuntu and still having the exact same error!!!
![Screenshot from 2022-02-01 11-38-54](https://user-images.githubusercontent.com/13992604/152030252-7c09de96-ac5d-4c69-8597-71de94df6c95.png)
