### ISSUE TITLE
hello TannerGilbert , did you have inference code for tensorflow 2 for mask rcnn

### ISSUE THREAD

**Issue by doctorai-in** [TannerGilbert/Tensorflow-Object-Detection-API-train-custom-Mask-R-CNN-model#7]
please provide eval code for mask rcnn tensorflow 2.4.1

**Comment by TannerGilbert** [comment]
You can use the inference code from my [Tensorflow-Object-Detection-with-Tensorflow-2.0 repo](https://github.com/TannerGilbert/Tensorflow-Object-Detection-with-Tensorflow-2.0).

**Comment by doctorai-in** [comment]
thanks TannerGilbert
